### ISSUE TITLE
Y/N Question for do you have kids

### ISSUE THREAD

**Issue by jeffslofish** [opensmc/get-connected-smc#21]
Get Connected SMC feedback:

- Create y/n question for do you have kids 
	- yes = kids questions for WIC/free and reduced price meals at school
	- no = no kid questions (household size, income, zip code)

**Comment by jeffslofish** [comment]
@jridener Can you clarify which questions should follow if they choose yes and if they choose no for if they have kids? Thanks!

**Comment by jridener** [comment]
Apologies for the shorthand in my notes. Here's some clarification.

All users are asked 
- Do you have children? y/n

If yes:
- Number of children 5 or under in your household: 0 - 5+
- Number of children in school in your household 1 - 8+
- If no questions below

If no:
- household size
- income
- pregnant
- zip code
- MediCal in the past 12 months
- CalFresh in the past 12 months

Additional changes to program eligibility logic are required as well since users who do not have kids aren't eligible for free or reduced price meals at school.

If children = yes AND number of children in school > 0 then check other eligibility requirements for free and reduced price lunch at school

If children = yes AND number of children in school = 0 not eligible for free and reduced price lunch at school

Hope that's more clear. Please let me know if not!
